name: Trivy Scan Action
description: Scan Docker images using Trivy and upload results.
inputs:
  image:
    description: A docker image
    required: true
  category:
    description: Unique category for the SARIF upload
    required: true
  path-to-dockerfile:
    description: Path to Dockerfile
    required: true

runs:
  using: composite
  steps:
  - name: Build Docker Second Image
    uses: docker/build-push-action@v4
    with:
      context: .
      file: ${{ inputs.path-to-dockerfile }}
      platforms: linux/amd64
      push: false
      tags: ${{ inputs.image }}

  - name: Run Trivy vulnerability scanner
    uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2
    with:
      image-ref: ${{ inputs.image }}
      format: sarif
      output: trivy-results-${{ inputs.images }}.sarif
      vuln-type: 'os,library'
      severity: 'CRITICAL,HIGH'

  - name: Upload Trivy scan results to GitHub Security tab
    uses: github/codeql-action/upload-sarif@662472033e021d55d94146f66f6058822b0b39fd
    with:
      sarif_file: trivy-results-${{ inputs.images }}.sarif
      category: ${{ inputs.category }}

