on:
  push:
    branches:
      - main

env:
  IMAGE_TAG: v2.0.5

jobs:
  extract-tag:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.update-tag.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract and update IMAGE_TAG
        id: update-tag # ID to reference this step
        run: |
          # Update the IMAGE_TAG value to the new version
          IMAGE_TAG="v2.0.6"
          vtag=IMAGE_TAG
          IMAGE_TAG=${vtag//v}
          # Set IMAGE_TAG as an output for this job
          echo "::set-output name=IMAGE_TAG::$IMAGE_TAG"

  use-image-tag:
    runs-on: ubuntu-latest
    needs: extract-tag # Specifies dependency on the extract-tag job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use the updated IMAGE_TAG
        run: |
          echo "Using the image tag from extract-tag: ${{ needs.extract-tag.outputs.IMAGE_TAG }}"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # - name: Extract version from tag
      #   run: |
      #     vtag=${{ env.IMAGE_TAG }}
      #     echo "Image--> ${vtag//v}"
      # echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV  # Set the environment variable
      # - name: Display Image Tag
      #   run: |
      #     echo "Image Tag is ${{ env.IMAGE_TAG }}"
